pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        PYTHONPATH = "${WORKSPACE}/E05-multistage-jenkins/.python_packages"
        PATH = "${WORKSPACE}/E05-multistage-jenkins/.python_packages/bin:${PATH}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Deps') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh '''
                        python -m pip install \
                          --target="$WORKSPACE/E05-multistage-jenkins/.python_packages" \
                          -r requirements.txt
                    '''
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'python -m pytest -v'
                }
            }
        }

        stage('Static Analysis') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'python -m flake8 app.py test_app.py'
                }
            }
        }

        stage('Deploy to Staging') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'echo "Deploying application to staging..."'
                    sh 'echo "Deployment successful!"'
                }
            }
        }
    }
}
