pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Deps') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'pytest -v'
                }
            }
        }

        stage('Static Analysis') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'flake8 app.py test_app.py'
                }
            }
        }

        stage('Deploy to Staging') {
            steps {
                dir('E05-multistage-jenkins') {
                    sh 'echo "Deploying application to staging..."'
                    sh 'echo "Deployment successful!"'
                }
            }
        }
    }
}
